# Generated by Django 6.0.2 on 2026-02-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.CharField(default='dafault.png', max_length=200),
        ),
    ]
